### ISSUE TITLE
Cgal slicing, differentiate open vs closed contours

### ISSUE THREAD

**Issue by ioannaMitropoulou** [compas-dev/compas_slicer#146]
The way Cgal slicer works:
  'for a closed geometry (and therefore closed path) the first and last point of the list are the same. So one can know whether the path is open or closed, but if it is open I'm not sure how to find out which point belongs to one path and which one to another' 

How to differentiate when there are multiple open paths from every level without making the process a lot slower?

**Comment by joburger** [comment]
This was solved some months ago
